import os

from dotenv import load_dotenv

load_dotenv()

# INDIAMART
INDIAMART_DB_USERNAME=os.getenv('INDIAMART_DB_USERNAME')
INDIAMART_DB_PASSWORD=os.getenv('INDIAMART_DB_PASSWORD')
INDIAMART_DB_NAME=os.getenv('INDIAMART_DB_NAME')
INDIAMART_DB_HOST=os.getenv('INDIAMART_DB_HOST')
INDIAMART_DB_PORT=os.getenv('INDIAMART_DB_PORT')

# AMEX
AMEX_DB_USERNAME=os.getenv('AMEX_DB_USERNAME')
AMEX_DB_PASSWORD=os.getenv('AMEX_DB_PASSWORD')
AMEX_DB_NAME=os.getenv('AMEX_DB_NAME')
AMEX_DB_HOST=os.getenv('AMEX_DB_HOST')
AMEX_DB_PORT=os.getenv('AMEX_DB_PORT')

# BUILDZOOM
BUILDZOOM_DB_USERNAME=os.getenv('BUILDZOOM_DB_USERNAME')
BUILDZOOM_DB_PASSWORD=os.getenv('BUILDZOOM_DB_PASSWORD')
BUILDZOOM_DB_NAME=os.getenv('BUILDZOOM_DB_NAME')
BUILDZOOM_DB_HOST=os.getenv('BUILDZOOM_DB_HOST')
BUILDZOOM_DB_PORT=os.getenv('BUILDZOOM_DB_PORT')

# DNB
DNB_DB_USERNAME=os.getenv('DNB_DB_USERNAME')
DNB_DB_PASSWORD=os.getenv('DNB_DB_PASSWORD')
DNB_DB_NAME=os.getenv('DNB_DB_NAME')
DNB_DB_HOST=os.getenv('DNB_DB_HOST')
DNB_DB_PORT=os.getenv('DNB_DB_PORT')

# NEXTDOOR
NEXTDOOR_DB_USER=os.getenv('NEXTDOOR_DB_USERNAME')
NEXTDOOR_DB_PASSWORD=os.getenv('NEXTDOOR_DB_PASSWORD')
NEXTDOOR_DB_NAME=os.getenv('NEXTDOOR_DB_NAME')
NEXTDOOR_DB_HOST=os.getenv('NEXTDOOR_DB_HOST')
NEXTDOOR_DB_PORT=os.getenv('NEXTDOOR_DB_PORT')
